function flashcardgwt(){var bb='',$=' top: -1000px;',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',hb='");',zb='#',kc='.cache.js',Bb='/',Hb='//',cc='305A8F91172AF849E00A69D2DA6E19F8',fc='6CD5CBAFA109D80D5BDB4583B03AD45D',gc='78766379F1EB029D8C4DF15D91FF4059',hc='9F9E4F6AF7DD967C84FADF4F08C6FB69',jc=':',dc=':1',ec=':2',qb='::',zc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',tb='=',Ab='?',vb='Bad handler "',ic='C2965FC5BBD817F3AEA10D2B4A2FABCE',_='CSS1Compat',fb='Chrome',eb='DOMContentLoaded',V='DUMMY',yc='Ignoring non-whitelisted Dev Mode URL: ',xc='__gwtDevModeHook:flashcardgwt',Qb='android',Gb='base',Eb='baseUrl',Q='begin',W='body',P='bootstrap',Db='clear.cache.gif',sb='content',rc='css/bootstrap.min.css',tc='css/font-awesome.min.css',sc='css/gwt-bootstrap.css',Rb='desktop',uc='end',gb='eval("',wc='file:',T='flashcardgwt',bc='flashcardgwt.devmode.js',Fb='flashcardgwt.nocache.js',pb='flashcardgwt::',Ib='formfactor',Zb='gecko',$b='gecko1_8',R='gwt.codesvr.flashcardgwt=',S='gwt.codesvr=',qc='gwt/clean/clean.css',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',mb='head',oc='href',vc='http:',Wb='ie10',Yb='ie8',Xb='ie9',X='iframe',Cb='img',Mb='ipad',Jb='iphone',Kb='ipod',jb='javascript',Y='javascript:""',lc='link',pc='loadExternalRefs',nb='meta',Lb='mobile',lb='moduleRequested',kb='moduleStartup',Vb='msie',ob='name',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',mc='rel',Ub='safari',ib='script',ac='selectingPermutation',U='startup',nc='stylesheet',Nb='tablet',Pb='touch',db='undefined',_b='unknown',Sb='user.agent',Tb='webkit',Ob='win';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
flashcardgwt.__sendStats=r;flashcardgwt.__moduleName=T;flashcardgwt.__errFn=null;flashcardgwt.__moduleBase=V;flashcardgwt.__softPermutationId=0;flashcardgwt.__computePropValue=null;flashcardgwt.__getPropMap=null;flashcardgwt.__gwtInstallCode=function(){};flashcardgwt.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=jb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=jb;g.text=c[i];e.appendChild(g);d(e,g)}}}
flashcardgwt.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(mb)[0].appendChild(n)}
flashcardgwt.__startLoadingFragment=function(a){return G(a)};flashcardgwt.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=jb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(nb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=0){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;flashcardgwt.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=t(Eb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Gb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return flashcardgwt.__moduleBase+a}
function H(){var g=[];var h;function i(a,b){var c=g;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
k[Ib]=function(){var a=navigator.userAgent.toLowerCase();var b=navigator.platform.toLowerCase();if(a.indexOf(Jb)!=-1||a.indexOf(Kb)!=-1){return Lb}else if(a.indexOf(Mb)!=-1){return Nb}else if(b.indexOf(Ob)!==-1&&a.indexOf(Pb)!=-1){return Nb}else if(a.indexOf(Qb)!=-1||a.indexOf(Lb)!=-1){var c=160;var d=o.screen.width/c;var e=o.screen.height/c;var f=Math.sqrt(d*d+e*e);return f<6?Lb:Nb}return Rb};j[Ib]={desktop:0,mobile:1,tablet:2};k[Sb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=10}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=9}())return Xb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=8}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};j[Sb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};s=function(a,b){return b in j[a]};flashcardgwt.__getPropMap=function(){var a={};for(var b in j){if(j.hasOwnProperty(b)){a[b]=l(b)}}return a};flashcardgwt.__computePropValue=l;o.__gwt_activeModules[T].bindings=flashcardgwt.__getPropMap;r(P,ac);if(q()){return G(bc)}var m;try{i([Rb,Yb],cc);i([Lb,Yb],cc);i([Nb,Yb],cc);i([Rb,Yb],cc+dc);i([Lb,Yb],cc+dc);i([Nb,Yb],cc+dc);i([Rb,Yb],cc+ec);i([Lb,Yb],cc+ec);i([Nb,Yb],cc+ec);i([Rb,$b],fc);i([Lb,$b],fc);i([Nb,$b],fc);i([Rb,$b],fc+dc);i([Lb,$b],fc+dc);i([Nb,$b],fc+dc);i([Rb,$b],fc+ec);i([Lb,$b],fc+ec);i([Nb,$b],fc+ec);i([Rb,Xb],gc);i([Lb,Xb],gc);i([Nb,Xb],gc);i([Rb,Xb],gc+dc);i([Lb,Xb],gc+dc);i([Nb,Xb],gc+dc);i([Rb,Xb],gc+ec);i([Lb,Xb],gc+ec);i([Nb,Xb],gc+ec);i([Rb,Ub],hc);i([Lb,Ub],hc);i([Nb,Ub],hc);i([Rb,Ub],hc+dc);i([Lb,Ub],hc+dc);i([Nb,Ub],hc+dc);i([Rb,Ub],hc+ec);i([Lb,Ub],hc+ec);i([Nb,Ub],hc+ec);i([Rb,Wb],ic);i([Lb,Wb],ic);i([Nb,Wb],ic);i([Rb,Wb],ic+dc);i([Lb,Wb],ic+dc);i([Nb,Wb],ic+dc);i([Rb,Wb],ic+ec);i([Lb,Wb],ic+ec);i([Nb,Wb],ic+ec);m=g[l(Ib)][l(Sb)];var n=m.indexOf(jc);if(n!=-1){h=parseInt(m.substring(n+1),10);m=m.substring(0,n)}}catch(a){}flashcardgwt.__softPermutationId=h;return G(m+kc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(lc);b.setAttribute(mc,nc);b.setAttribute(oc,G(a));p.getElementsByTagName(mb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(pc,Q);c(qc);c(rc);c(sc);c(tc);r(pc,uc)}
D();flashcardgwt.__moduleBase=F();u[T].moduleBase=flashcardgwt.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==vc||o.location.protocol==wc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=xc;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(yc+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+zc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(mb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,uc);C(J);return true}
flashcardgwt.succeeded=flashcardgwt();